### ISSUE TITLE
my life is broek

### ISSUE THREAD

**Issue by mathjaden** [mdhack/help#2]
package bot;

import java.util.ArrayList;

import net.dv8tion.jda.core.entities.Message;
import net.dv8tion.jda.core.entities.MessageChannel;
import net.dv8tion.jda.core.events.message.MessageReceivedEvent;
import net.dv8tion.jda.core.hooks.ListenerAdapter;

public class BotVoting extends ListenerAdapter{

	public void onMessageReceived(MessageReceivedEvent input) {

		String pollname;
		Boolean done = false;
		ArrayList<String> categories = new ArrayList<String>(2);

		if(input.getMessage().getRawContent().equals("startPoll"))
			input.getChannel().sendMessage("What Do You Want To Call It? Use setName=").queue();

		if((input.getMessage().getRawContent().contains("setName=") == true)){
			input.getChannel().sendMessage("penis");

			pollname = input.getMessage().getRawContent().substring(8);
			input.getChannel().sendMessage("Pollname set as " + pollname);

			do{
				input.getChannel().sendMessage("What is the First Category?");
				categories.add(input.getMessage().getRawContent());
				input.getChannel().sendMessage("Are You Done? Yes or No");
				if(input.getMessage().equals("Yes"))
					done = true;
			}while(done = false);
		}

	}
}

**Comment by mathjaden** [comment]
nvm i forgot .queue

**Comment by itsmingjie** [comment]
Closing: Solved.
